### ISSUE TITLE
Favorite Button or Love Button doesn't Work

### ISSUE THREAD

**Issue by volcbs** [akameco/PixivDeck#109] opened 2017-07-13 16:05 UTC
OS = MacOS 10.12.5
PixivDeck version = 0.14.2

It can't be clicked at all, there's no problem when I used 0.12.1 though.
![out](https://user-images.githubusercontent.com/12575216/28175707-2dcb4056-681f-11e7-8dc9-24216ee800df.gif)

**Comment by akameco** [comment] 2017-07-13 22:39
@volcbs  Thank you for your report!

Well, probably the bookmark is successful.
You can confirm by addind bookmark column.
Because if you do not have a bookmark column it will not run screen update processing.

But, I think this behavior is hard to understand.
So, I will fix it today.

**Comment by volcbs** [comment] 2017-07-14 01:49
Thanks, it works now!
But still, you need to click twice to make this works. Can you fix this, please?

**Comment by akameco** [comment] 2017-07-14 02:52
That's strange.
I have not happened in my environment.
I will investigate.

**Comment by volcbs** [comment] 2017-07-14 14:33
In fact, I find it weird too.
It's like this in my macOS.
![2017-07-14 21 25 45](https://user-images.githubusercontent.com/12575216/28216307-53d3ec32-68db-11e7-8cb4-0c56ddcc13ac.gif)

You also can't do 'unfavorite.'
![2017-07-14 21 25 58](https://user-images.githubusercontent.com/12575216/28216308-5485eac2-68db-11e7-98de-b872660adcf8.gif)

And I also find something interesting, your columns could be gone by something like this. 
1. Open pixivdeck
2. Close the app from windows bar
3. Quit it from menu bar
Your columns will be gone after that. I think it will be better if you can quit the apps with just clicking close from the windows bar.

**Comment by akameco** [comment] 2017-07-15 09:43
Thank you for your reporting.

> unfavorite

Oops! I confirmed it in my environment. I will fix it!

> columns could be gone

Umm, I' ll investigate.

> I think it will be better if you can quit the apps with just clicking close from the windows bar.

For most Mac applications the window bar's close button acts as a hidden.
PixivDeck does that as well.
I recommended using `⌘q` for closing app 👍

**Closed** 2017-07-28 13:14 UTC
